"""Initial migration

Revision ID: 79477a1a8dc8
Revises: d43e7abfd8e0
Create Date: 2025-01-08 20:54:56.951466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79477a1a8dc8'
down_revision = 'd43e7abfd8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('tournament')
    # ### end Alembic commands ###
